### ISSUE TITLE
Euroleague player live stats per match

### ISSUE THREAD

**Issue by BernD3v** [FlavioLeccese92/euroleaguer#1]
I stumbled upon your API while researching EuroLeague statistics. I am interested in retrieving live player statistics in real time for each EuroLeague match. Could you please confirm if it is possible to obtain live stats for specific players during the matches using your API? If so, could you provide an example on how to achieve this?

Thanks, this project looks really cool!

**Comment by FlavioLeccese92** [comment]
Hi @BernD3v, sorry for being late.
I'll look it up during this winter break and get back to you with an answer, thank you for your patience!

**Comment by FlavioLeccese92** [comment]
In order to access players' statistics of ongoing games you need to retrieve some information and concatenate a few API calls.
Specifically, `getGameBoxScore` can be called on an ongoing game if the code name is known.

```
library(euroleaguer)
library(dplyr)

# Get rounds in the past or in progress
competition_rounds = getCompetitionRounds(
  season_code = "E2024"
  ) %>% 
  filter(MinGameStartDate <= Sys.Date())

# Get games for rounds of interest
competition_games = getCompetitionGames(
  season_code = "E2024", 
  round = competition_rounds$Round
  )

# Get game game box for games of the last round
# If some of the games are ongoing, the column Status for that game is set to "live"
competition_games_lr = competition_games %>% slice_max(Round)
game_box_score_lr = getGameBoxScore(
  season_code = "E2024",
  game_code = competition_games_lr$GameCode
  )

# Extract player statistics for last round games
player_stats_lr = game_box_score_lr$PlayerStats
```

Let me know if it is clear or if you needed something different
